M48
; DRILL file {KiCad 7.0.7} date Mon Mar  4 03:02:10 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-04T03:02:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X25.605Y-40.11
X25.605Y-45.89
T2
X23.0Y-52.0
X52.0Y-23.0
T0
M30
